version: '3.1'

services:
  php-fpm:
    build: ./php-fpm
    container_name: php-fpm
    restart: always
    volumes:
      - /usr/share/code:/code
      - /usr/share/log:/log
      - /usr/share/config/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - /usr/share/config/www.conf:/usr/local/etc/php-fpm.d/www.conf
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /usr/share/code:/code
    links:
      - php-fpm
  