version: '3.1'

services:
  database:
    image: mysql:5.5
    container_name: database
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: mockProject
      MYSQL_USER: vagrant
      MYSQL_PASSWORD: vagrant